### ISSUE TITLE
Best settings for DSub?

### ISSUE THREAD

**Issue by sardaukar** [sentriz/gonic#13]
Anyone seen this issue before?

![photo5972136799885176800](https://user-images.githubusercontent.com/153407/69532550-f84eff00-0f6d-11ea-9087-96ac50b210ef.jpg)

I get it navigating to some folders in my Library view. On the gonic logs, I just see a successful request

`/rest/getMusicDirectory.view?u=admin&p=enc:<OMITTED>&v=1.2.0&c=DSub&id=8330`

**Comment by sentriz** [comment]
Hmm I have no idea what that is. Could you show the output when curling the above link?

**Comment by sardaukar** [comment]
[output.xml.zip](https://github.com/sentriz/gonic/files/3886205/output.xml.zip)

I had to add `-L` to curl to follow the initial 301

**Comment by sentriz** [comment]
still having trouble reproducing. what version of dsub are you running?

**Comment by sardaukar** [comment]
The latest on the Play Store (at least for me) is 5.4.4

**Comment by sentriz** [comment]
WOWWsjdhfksjfdkJHHKJJJJJJJHAKSSShjW
HHHH

**Comment by sentriz** [comment]
hmmm. did that folder work for your old subsonic server? and if so would it be possible to show the curl of that so I could compare the two responses? thank you

**Comment by sardaukar** [comment]
Let me just try to replicate the curl.

**Comment by sardaukar** [comment]
Here's with Airsonic (my Subsonic fork, that works 100% with DSub)

[output_airsonic.zip](https://github.com/sentriz/gonic/files/3889393/output_airsonic.zip)

**Comment by sardaukar** [comment]
Looks like `gonic`s timestamps are always `0001-01-01T00:00:00Z` which might trip DSub up

**Comment by sentriz** [comment]
thank you for that output. will be very helpful for debugging. I just pushed an update (it's building on dockerhub right now) 
it always returns isDir/isVideo correctly for `getMusicDirectory` (since dsub is giving you errors about bools) and also returns timestamps correctly as you said. 

would you mind trying this one out?

**Comment by sardaukar** [comment]
Will try!

**Comment by sardaukar** [comment]
Ok so still have the same DSub error :( here's another dump of 2 directories, one working the other not (the same as the original XML error dump)
[outputs.zip](https://github.com/sentriz/gonic/files/3892463/outputs.zip)

**Comment by sentriz** [comment]
strange. can you try one more thing?

install the latest dsub from github (I remember a difference in the play store and github versions)

https://github.com/daneren2005/Subsonic/releases/download/5.4.4/DSub.5.4.4.apk

**Comment by sardaukar** [comment]
Same thing on this version from Github. Something about this folder's output makes it crash out :( I can give you an account on my server to test it out if you'd like.

**Comment by sentriz** [comment]
ok thanks for trying and the outputs. going to try `diffxml` now to see what might differ between the servers

**Comment by sentriz** [comment]
hey would you minding sending me an email if you're still interesting in this? i have a different idea. thanks!

**Comment by sardaukar** [comment]
Thanks for sticking with this - seems to work fine now! :D
